### PR TITLE
feat: activate LDAP by default

### PR DESCRIPTION
**Pull request by asandikci**
Installation page says app is LDAP compatible. I don't see any reason to deactivate it as default. Either merge this PR or Update README.md to inform users for configuring settings in /var/www/leantime/config/.env with [Documentation](https://github.com/Leantime/docs/blob/master/installation/configuration.md)

(FYI: also SMTP or default php mail() function is not working with this .env file)

### CODE REVIEW

**Comment by asandikci** [comment]
CRITICAL UPDATE: Enabling LDAP also causes non-authorised users to log in. I tried to resolve problem but could not find a variable to change permissions as seen in https://yunohost.org/en/packaging_sso_ldap_integration#ldap-integration in section **Search filter:** `(&(|(objectclass=posixAccount))(uid=%uid)(permission=cn=__APP__.main,ou=permission,dc=yunohost,dc=org))`

**Comment by asandikci** [comment]
UPDATE 2: When trying to log in leantime without yunohost login, its already redirects to yunohost SSO page. So this problem is not critical, and I guess even we can say there is no problem without a search filter. 

I was just logged in yunohost portal with another user(allowed for leantime) and tried to log in leantime with 2nd user(not allowing for leantime). That's why I just thought there was a problem with it 😅

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
Closing with #13

**Pull request closed without merging**
