### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Review by alexAubin — APPROVED** [review]
LGTM, apparently the change url thing is not a regression because it's already not working on the master branch

**Comment by CodeShakingSheep** [comment]
What's preventing this from getting merged @ericgaspar?

**Comment by ericgaspar** [comment]
!testme

**Comment by CodeShakingSheep** [comment]
Thanks a lot @ericgaspar ! Works fine :)

**Pull request merged**
